spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

security:
  ignored: /**

application:
  gcp:
    maps:
      apiKey: #Change to custom API KEY for google maps.
eureka:
  instance:
    hostname: localhost